"""Add title to LegalBriefRevision and refactor brief_id to legal_brief_id in router

Revision ID: 51abf775556a
Revises: 6c56393899c3
Create Date: 2025-10-23 10:14:36.452541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51abf775556a'
down_revision: Union[str, Sequence[str], None] = '6c56393899c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_brief_revisions', sa.Column('title', sa.Text(), nullable=False, server_default='Título Padrão (Preenchimento de Migração)'))
    op.drop_column('legal_briefs', 'canceled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_briefs', sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('legal_brief_revisions', 'title')
    # ### end Alembic commands ###
