"""add audit fields to Notice

Revision ID: 563da3e3f296
Revises: f3852c2fbc83
Create Date: 2025-11-17 15:31:58.114088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '563da3e3f296'
down_revision: Union[str, Sequence[str], None] = 'f3852c2fbc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice_reads', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False))
    op.add_column('notice_reads', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notice_reads', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notice_reads', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('notice_reads', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('notice_reads', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notice_reads', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notice_reads', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notice_reads', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('notice_reads', 'read_at')
    op.add_column('notices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notices', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('notices', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('notices', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.alter_column('notices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'notices', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notices', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notices', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.alter_column('notices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('notices', 'deleted_by_id')
    op.drop_column('notices', 'updated_by_id')
    op.drop_column('notices', 'created_by_id')
    op.drop_column('notices', 'deleted_at')
    op.drop_column('notices', 'updated_at')
    op.add_column('notice_reads', sa.Column('read_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notice_reads', type_='foreignkey')
    op.drop_constraint(None, 'notice_reads', type_='foreignkey')
    op.drop_constraint(None, 'notice_reads', type_='foreignkey')
    op.drop_column('notice_reads', 'deleted_by_id')
    op.drop_column('notice_reads', 'updated_by_id')
    op.drop_column('notice_reads', 'created_by_id')
    op.drop_column('notice_reads', 'deleted_at')
    op.drop_column('notice_reads', 'updated_at')
    op.drop_column('notice_reads', 'created_at')
    # ### end Alembic commands ###
