"""Tornar created_by_id non-nullable no AuditMixin

Revision ID: 57bbc6ed1255
Revises: d330796886be
Create Date: 2025-11-17 16:29:31.780490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bbc6ed1255'
down_revision: Union[str, Sequence[str], None] = 'd330796886be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notice_reads', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_notice_user_read'), 'notice_reads', type_='unique')
    op.create_unique_constraint('uq_notice_user_read', 'notice_reads', ['created_by_id', 'notice_id'])
    op.drop_constraint(op.f('notice_reads_user_id_fkey'), 'notice_reads', type_='foreignkey')
    op.drop_column('notice_reads', 'user_id')
    op.alter_column('notices', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('notice_reads', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notice_reads_user_id_fkey'), 'notice_reads', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_notice_user_read', 'notice_reads', type_='unique')
    op.create_unique_constraint(op.f('uq_notice_user_read'), 'notice_reads', ['user_id', 'notice_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('notice_reads', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
