"""added CANCELED in LoanStatus

Revision ID: 6c5a94a99d86
Revises: a82cf7715833
Create Date: 2025-11-05 17:36:36.128694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5a94a99d86'
down_revision: Union[str, Sequence[str], None] = 'a82cf7715833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE loanstatus ADD VALUE 'CANCELED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
