"""added CANCELED in LoanStatus

Revision ID: 835e9b44a17c
Revises: a06ab1b897cb
Create Date: 2025-11-05 12:07:25.215017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835e9b44a17c'
down_revision: Union[str, Sequence[str], None] = 'a06ab1b897cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
