"""added CANCELLED in LoanStatus

Revision ID: a06ab1b897cb
Revises: a82cf7715833
Create Date: 2025-11-05 11:40:38.792637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06ab1b897cb'
down_revision: Union[str, Sequence[str], None] = 'a82cf7715833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
