"""refactor vacation to accrual periods and grants

Revision ID: a911d5bbe8d1
Revises: ad24530970ef
Create Date: 2026-08-04 14:53:48.547585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a911d5bbe8d1'
down_revision: Union[str, Sequence[str], None] = 'ad24530970ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_accrual_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('acquisitive_start', sa.Date(), nullable=False),
    sa.Column('acquisitive_end', sa.Date(), nullable=False),
    sa.Column('concessive_start', sa.Date(), nullable=False),
    sa.Column('concessive_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCESSIVE', 'EXPIRED', 'CLOSED', name='vacation_accrual_status_enum'), nullable=False),
    sa.Column('days_earned', sa.Integer(), nullable=False),
    sa.Column('days_reserved', sa.Integer(), nullable=False),
    sa.Column('days_enjoyed', sa.Integer(), nullable=False),
    sa.Column('days_sold', sa.Integer(), nullable=False),
    sa.Column('days_double_paid', sa.Integer(), nullable=False),
    sa.Column('is_double_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_number', name='uq_accrual_user_period')
    )
    op.create_table('vacation_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accrual_period_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.Enum('NORMAL', 'RETROACTIVE', 'DOUBLE_PAYMENT', name='vacation_grant_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'IN_PROGRESS', 'FRUITED', 'CANCELLED', 'PAID_DOUBLE', name='vacation_grant_status_enum'), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accrual_period_id'], ['vacation_accrual_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vacation_historical_periods')
    op.drop_table('vacation_balances')
    op.drop_column('vacation_periods', 'working_days_count')
    op.drop_column('vacation_periods', 'status')
    op.add_column('vacation_requests', sa.Column('target_accrual_period_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vacation_requests', 'vacation_accrual_periods', ['target_accrual_period_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacation_requests', type_='foreignkey')
    op.drop_column('vacation_requests', 'target_accrual_period_id')
    op.add_column('vacation_periods', sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ENJOYED', name='vacation_status_enum'), autoincrement=False, nullable=False))
    op.add_column('vacation_periods', sa.Column('working_days_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('vacation_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('current_period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('accrued_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proportional_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enjoyed_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sold_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manual_adjustment_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adjustment_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adjusted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('adjusted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_period_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_accrued_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by_id'], ['users.id'], name=op.f('vacation_balances_adjusted_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('vacation_balances_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('vacation_balances_deleted_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('vacation_balances_updated_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vacation_balances_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vacation_balances_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('vacation_balances_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('vacation_historical_periods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acquisitive_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('acquisitive_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('enjoyed_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('enjoyed_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('base_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_double', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('vacation_historical_periods_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('vacation_historical_periods_deleted_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('vacation_historical_periods_updated_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vacation_historical_periods_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vacation_historical_periods_pkey')),
    sa.UniqueConstraint('user_id', 'acquisitive_start', name=op.f('uq_historical_user_acquisitive'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('vacation_grants')
    op.drop_table('vacation_accrual_periods')
    # ### end Alembic commands ###
