"""add phone and gross salary to users

Revision ID: b061be051fe4
Revises: 39ee918fcd37
Create Date: 2026-09-12 09:03:54.105016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b061be051fe4'
down_revision: Union[str, Sequence[str], None] = '39ee918fcd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gross_salary', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gross_salary')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
