"""Add audit fields and cancellation tracking to LegalBrief and LegalBriefRevision.

Revision ID: bf7369b00cc3
Revises: 57bbc6ed1255
Create Date: 2025-11-17 17:40:31.059010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf7369b00cc3'
down_revision: Union[str, Sequence[str], None] = '57bbc6ed1255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_brief_revisions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_brief_revisions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_brief_revisions', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('legal_brief_revisions', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.alter_column('legal_brief_revisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('legal_brief_revisions', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('legal_brief_revisions_updated_by_id_fkey'), 'legal_brief_revisions', type_='foreignkey')
    op.create_foreign_key(None, 'legal_brief_revisions', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_brief_revisions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_brief_revisions', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('legal_briefs', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_briefs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_briefs', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.alter_column('legal_briefs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('legal_briefs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('legal_briefs_updated_by_id_fkey'), 'legal_briefs', type_='foreignkey')
    op.drop_constraint(op.f('legal_briefs_created_by_id_fkey'), 'legal_briefs', type_='foreignkey')
    op.create_foreign_key(None, 'legal_briefs', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_briefs', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_briefs', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'legal_briefs', type_='foreignkey')
    op.drop_constraint(None, 'legal_briefs', type_='foreignkey')
    op.drop_constraint(None, 'legal_briefs', type_='foreignkey')
    op.create_foreign_key(op.f('legal_briefs_created_by_id_fkey'), 'legal_briefs', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('legal_briefs_updated_by_id_fkey'), 'legal_briefs', 'users', ['updated_by_id'], ['id'])
    op.alter_column('legal_briefs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('legal_briefs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('legal_briefs', 'deleted_by_id')
    op.drop_column('legal_briefs', 'deleted_at')
    op.drop_column('legal_briefs', 'canceled_at')
    op.drop_constraint(None, 'legal_brief_revisions', type_='foreignkey')
    op.drop_constraint(None, 'legal_brief_revisions', type_='foreignkey')
    op.drop_constraint(None, 'legal_brief_revisions', type_='foreignkey')
    op.create_foreign_key(op.f('legal_brief_revisions_updated_by_id_fkey'), 'legal_brief_revisions', 'users', ['updated_by_id'], ['id'])
    op.alter_column('legal_brief_revisions', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('legal_brief_revisions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('legal_brief_revisions', 'deleted_by_id')
    op.drop_column('legal_brief_revisions', 'created_by_id')
    op.drop_column('legal_brief_revisions', 'deleted_at')
    op.drop_column('legal_brief_revisions', 'updated_at')
    # ### end Alembic commands ###
