"""include canceled fields in LegalBrief model

Revision ID: d2d44339a757
Revises: 76111aa7edf7
Create Date: 2025-10-17 10:03:01.413564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d44339a757'
down_revision: Union[str, Sequence[str], None] = '76111aa7edf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_briefs', sa.Column('canceled_by_id', sa.Integer(), nullable=True))
    op.add_column('legal_briefs', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'legal_briefs', 'users', ['canceled_by_id'], ['id'])
    op.drop_column('legal_briefs', 'created_at')
    op.drop_column('legal_briefs', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_briefs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('legal_briefs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'legal_briefs', type_='foreignkey')
    op.drop_column('legal_briefs', 'canceled_at')
    op.drop_column('legal_briefs', 'canceled_by_id')
    # ### end Alembic commands ###
