"""Remove user_id from Notice

Revision ID: d330796886be
Revises: 563da3e3f296
Create Date: 2025-11-17 15:40:19.303470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd330796886be'
down_revision: Union[str, Sequence[str], None] = '563da3e3f296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notices_user_id_fkey'), 'notices', type_='foreignkey')
    op.drop_column('notices', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notices_user_id_fkey'), 'notices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
