"""add password_reset_tokens table for tracking used reset tokens

Revision ID: e4febf87d605
Revises: 91824b5b3789
Create Date: 2025-11-26 10:42:12.722233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4febf87d605'
down_revision: Union[str, Sequence[str], None] = '91824b5b3789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
