"""fix: explicit foreign_keys and defaults in LegalBrief

Revision ID: f98572e18b6a
Revises: d2d44339a757
Create Date: 2025-10-17 10:20:23.231829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98572e18b6a'
down_revision: Union[str, Sequence[str], None] = 'd2d44339a757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_briefs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('legal_briefs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_briefs', 'updated_at')
    op.drop_column('legal_briefs', 'created_at')
    # ### end Alembic commands ###
